[package]
edition = "2021"
name = "platz-status-updates"
version = "0.1.0"

[dependencies]
anyhow = "1.0.86"
chrono = {version = "0.4.38", default-features = false, features = ["std", "serde"]}
clap = {version = "4.5.9", features = ["derive"]}
futures = "0.3.30"
platz-chart-ext = {workspace = true}
reqwest = {version = "0.12.5", default-features = false, features = ["rustls-tls", "json"]}
serde = {version = "1.0.204", features = ["derive"]}
serde_json = "1.0.120"
tokio = {version = "1.38.1", features = ["full"]}
tracing = "0.1.40"
tracing-subscriber = {workspace = true}
url = "2.5.2"
uuid = {version = "1.10.0", features = ["serde", "v4"]}

[dependencies.platz-db]
path = "../db"
