[package]
edition = "2021"
name = "platz-status-updates"
version = "0.1.0"

[dependencies]
anyhow = "1.0.71"
chrono = {version = "0.4.26", default-features = false, features = ["std", "serde"]}
clap = {version = "4.3.11", features = ["derive"]}
env_logger = "0.10.0"
futures = "0.3.28"
futures-util = "0.3.28"
log = "0.4.19"
platz-chart-ext = {workspace = true}
reqwest = {version = "0.11.18", default-features = false, features = ["rustls-tls", "json"]}
serde = {version = "1.0.171", features = ["derive"]}
serde_json = "1.0.100"
tokio = {version = "1.29.1", features = ["full"]}
url = "2.4.0"
uuid = {version = "1.4.0", features = ["serde", "v4"]}

[dependencies.platz-db]
path = "../db"
