[package]
edition = "2021"
name = "platz-status-updates"
version = "0.1.0"

[dependencies]
anyhow = "1.0.44"
chrono = {version = "0.4", features = ["std", "serde"]}
env_logger = "0.9.0"
futures = "0.3.17"
futures-util = "0.3.17"
log = "0.4.14"
reqwest = {version = "0.11.4", features = ["rustls-tls", "json"]}
serde = {version = "1", features = ["derive"]}
serde_json = "1"
structopt = "0.3.25"
tokio = {version = "1", features = ["full"]}
url = "2.2.2"
uuid = {version = "0.8", features = ["serde", "v4"]}

[dependencies.platz-chart-ext]
path = "../chart-ext"

[dependencies.platz-db]
path = "../db"
