[package]
edition = "2021"
name = "platz-status-updates"
version = "0.1.0"

[dependencies]
anyhow = "1.0.75"
chrono = {version = "0.4.31", default-features = false, features = ["std", "serde"]}
clap = {version = "4.4.4", features = ["derive"]}
futures = "0.3.28"
futures-util = "0.3.28"
log = "0.4.20"
platz-chart-ext = {workspace = true}
reqwest = {version = "0.11.20", default-features = false, features = ["rustls-tls", "json"]}
serde = {version = "1.0.188", features = ["derive"]}
serde_json = "1.0.107"
tokio = {version = "1.32.0", features = ["full"]}
tracing-subscriber = {workspace=true}
url = "2.4.1"
uuid = {version = "1.4.1", features = ["serde", "v4"]}

[dependencies.platz-db]
path = "../db"
