[package]
edition = "2021"
name = "platz-status-updates"
version = "0.1.0"

[dependencies]
anyhow = "1.0.79"
chrono = {version = "0.4.33", default-features = false, features = ["std", "serde"]}
clap = {version = "4.4.18", features = ["derive"]}
futures = "0.3.30"
futures-util = "0.3.30"
log = "0.4.20"
platz-chart-ext = {workspace = true}
reqwest = {version = "0.11.24", default-features = false, features = ["rustls-tls", "json"]}
serde = {version = "1.0.196", features = ["derive"]}
serde_json = "1.0.113"
tokio = {version = "1.35.1", features = ["full"]}
tracing-subscriber = {workspace=true}
url = "2.5.0"
uuid = {version = "1.7.0", features = ["serde", "v4"]}

[dependencies.platz-db]
path = "../db"
