replicaCount: 1

images:
  backend:
    image: ""
    repository: ""
    tag: ""
    pullPolicy: IfNotPresent
  helm:
    image: ""
    repository: ""
    tag: ""
    pullPolicy: IfNotPresent

config:
  api:
    auth:
      oidc_server_url: "https://accounts.google.com"
      ssm:
        oidc_client_id: ""
        oidc_client_secret: ""
  ecr_events:
    queue_name: ""
    region_name: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  api:
    name: platz-api
    annotations: {}
  taskRunner:
    name: platz-task-runner
    annotations: {}
  chartDiscovery:
    name: platz-chart-discovery
    annotations: {}
  statusUpdates:
    name: platz-status-updates
    annotations: {}

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

resources: {}
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

postgresql:
  nameOverride: postgresql
  postgresqlUsername: postgres
  postgresqlPassword: postgres
  postgresqlDatabase: platz
