[workspace]
members = [
  "api",
  "auth",
  "chart-discovery",
  "db",
  "k8s-agent",
  "resource-sync",
  "status-updates",
]
resolver = "2"

[profile.release]
debug = true

[workspace.dependencies.platz-chart-ext]
features = ["utoipa"]
version = "0.5.7"

[workspace.dependencies.tracing-subscriber]
version = "0.3.17"
features = ["env-filter", "fmt"]
