version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 15432:5432
  idp:
    image: dexidp/dex
    volumes:
      - ./scripts/dex.config.yaml:/etc/dex/config.docker.yaml:ro
    ports:
      - 5556:5556
  platz-api:
    build:
      context: .
      args:
        BASE_IMAGE: platzio/base:v6
        RELEASE_BUILD: 0
    command:
      - /root/platz-api
      - run
    environment:
      ADMIN_EMAILS: admin@example.com
      DATABASE_URL: postgres://postgres:postgres@db:5432
      OIDC_SERVER_URL: http://idp:5556
      OIDC_CLIENT_ID: foo
      OIDC_CLIENT_SECRET: bar
      PLATZ_OWN_URL: https://localhost:8080
    ports:
      - 3000:3000
