[package]
edition = "2021"
name = "platz-chart-discovery"
version = "0.1.0"

[dependencies]
anyhow = "1.0.43"
chrono = {version = "0.4", features = ["std", "serde"]}
clap = {version = "3.1.6", features = ["derive", "env"]}
env_logger = "0.9.0"
itertools = "0.10.1"
log = "0.4.14"
platz-chart-ext = {version = "0.4.0", default-features = false, features = ["uuid08"]}
regex = "1.5.6"
rusoto_core = {version = "0.48.0", default-features = false, features = ["rustls"]}
rusoto_ecr = {version = "0.48.0", default-features = false, features = ["rustls"]}
rusoto_sqs = {version = "0.48.0", default-features = false, features = ["rustls"]}
serde = {version = "1", features = ["derive"]}
serde_json = "1"
thiserror = "1"
titlecase = "2.0.0"
tokio = {version = "1", features = ["full"]}
uuid = {version = "0.8", features = ["serde", "v4"]}

[dependencies.platz-db]
path = "../db"

[dependencies.rusoto-utils]
path = "../rusoto-utils"
