[package]
edition = "2021"
name = "platz-chart-discovery"
version = "0.1.0"

[dependencies]
anyhow = "1.0.79"
aws-config = "1.1.4"
aws-sdk-ecr = "1.12.0"
aws-sdk-sqs = "1.12.0"
aws-smithy-types-convert = {version = "0.60.4", features = ["convert-chrono"]}
aws-types = "1.1.4"
chrono = {version = "0.4.33", default-features = false, features = ["std", "serde"]}
clap = {version = "4.4.18", features = ["derive", "env"]}
futures = "0.3.30"
itertools = "0.12.1"
log = "0.4.20"
platz-chart-ext = {workspace = true}
regex = "1.10.3"
serde = {version = "1.0.196", features = ["derive"]}
serde_json = "1.0.113"
thiserror = "1.0.56"
titlecase = "2.2.1"
tokio = {version = "1.35.1", features = ["full"]}
uuid = {version = "1.7.0", features = ["serde", "v4"]}

[dependencies.platz-db]
path = "../db"
