[package]
edition = "2021"
name = "platz-chart-discovery"
version = "0.1.0"

[dependencies]
anyhow = "1.0.86"
aws-config = "1.5.4"
aws-sdk-ecr = "1.35.0"
aws-sdk-sqs = "1.35.0"
aws-smithy-types-convert = { version = "0.60.8", features = ["convert-chrono"] }
aws-types = "1.3.3"
chrono = { version = "0.4.38", default-features = false, features = [
    "std",
    "serde",
] }
clap = { version = "4.5.9", features = ["derive", "env"] }
futures = "0.3.30"
itertools = "0.13.0"
platz-chart-ext = { workspace = true }
regex = "1.10.5"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
titlecase = "3.3.0"
tokio = { version = "1.38.1", features = ["full"] }
tracing = "0.1.40"
uuid = { version = "1.10.0", features = ["serde", "v4"] }

[dependencies.platz-db]
path = "../db"
