[package]
edition = "2021"
name = "platz-chart-discovery"
version = "0.1.0"

[dependencies]
anyhow = "1.0.71"
aws-config = "0.55.3"
aws-sdk-ecr = "0.28.0"
aws-sdk-sqs = "0.28.0"
aws-smithy-types-convert = {version = "0.55.3", features = ["convert-chrono"]}
aws-types = "0.55.3"
chrono = {version = "0.4.26", default-features = false, features = ["std", "serde"]}
clap = {version = "4.3.11", features = ["derive", "env"]}
env_logger = "0.10.0"
futures = "0.3.28"
itertools = "0.11.0"
log = "0.4.19"
platz-chart-ext = "0.5.7"
regex = "1.9.1"
serde = {version = "1.0.171", features = ["derive"]}
serde_json = "1.0.100"
thiserror = "1.0.43"
titlecase = "2.2.1"
tokio = {version = "1.29.1", features = ["full"]}
uuid = {version = "1.4.0", features = ["serde", "v4"]}

[dependencies.platz-db]
path = "../db"
