[package]
edition = "2021"
name = "platz-chart-discovery"
version = "0.1.0"

[dependencies]
anyhow = "1.0.75"
aws-config = "0.56.1"
aws-sdk-ecr = "0.31.0"
aws-sdk-sqs = "0.31.0"
aws-smithy-types-convert = {version = "0.56.1", features = ["convert-chrono"]}
aws-types = "0.56.1"
chrono = {version = "0.4.31", default-features = false, features = ["std", "serde"]}
clap = {version = "4.4.4", features = ["derive", "env"]}
futures = "0.3.28"
itertools = "0.11.0"
log = "0.4.20"
platz-chart-ext = {workspace = true}
regex = "1.9.5"
serde = {version = "1.0.188", features = ["derive"]}
serde_json = "1.0.107"
thiserror = "1.0.48"
titlecase = "2.2.1"
tokio = {version = "1.32.0", features = ["full"]}
uuid = {version = "1.4.1", features = ["serde", "v4"]}

[dependencies.platz-db]
path = "../db"
