[package]
edition = "2021"
name = "platz-chart-discovery"
version = "0.1.0"

[dependencies]
anyhow = "1.0.75"
aws-config = "1.0.0"
aws-sdk-ecr = "0.39.0"
aws-sdk-sqs = "0.39.0"
aws-smithy-types-convert = {version = "0.60.0", features = ["convert-chrono"]}
aws-types = "1.0.0"
chrono = {version = "0.4.31", default-features = false, features = ["std", "serde"]}
clap = {version = "4.4.8", features = ["derive", "env"]}
futures = "0.3.29"
itertools = "0.12.0"
log = "0.4.20"
platz-chart-ext = {workspace = true}
regex = "1.10.2"
serde = {version = "1.0.193", features = ["derive"]}
serde_json = "1.0.108"
thiserror = "1.0.50"
titlecase = "2.2.1"
tokio = {version = "1.34.0", features = ["full"]}
uuid = {version = "1.6.1", features = ["serde", "v4"]}

[dependencies.platz-db]
path = "../db"
