[package]
edition = "2021"
name = "platz-chart-discovery"
version = "0.1.0"

[dependencies]
anyhow = "1.0.43"
aws-config = "0.55.0"
aws-sdk-ecr = "0.28.0"
aws-sdk-sqs = "0.28.0"
aws-smithy-types-convert = {version = "0.55.0", features = ["convert-chrono"]}
aws-types = "0.55.0"
chrono = {version = "0.4", default-features = false, features = ["std", "serde"]}
clap = {version = "4.0.32", features = ["derive", "env"]}
env_logger = "0.10.0"
futures = "0.3.28"
itertools = "0.10.1"
log = "0.4.14"
platz-chart-ext = "0.5.5"
regex = "1.5.6"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
thiserror = "1"
titlecase = "2.0.0"
tokio = {version = "1", features = ["full"]}
uuid = {version = "1", features = ["serde", "v4"]}

[dependencies.platz-db]
path = "../db"
