[package]
edition = "2021"
name = "platz-chart-discovery"
version = "0.1.0"

[dependencies]
anyhow = "1.0.87"
aws-config = "1.5.6"
aws-sdk-ecr = "1.44.0"
aws-sdk-sqs = "1.42.0"
aws-smithy-types-convert = { version = "0.60.8", features = ["convert-chrono"] }
aws-types = "1.3.3"
chrono = { version = "0.4.38", default-features = false, features = [
    "std",
    "serde",
] }
clap = { version = "4.5.17", features = ["derive", "env"] }
futures = "0.3.30"
itertools = "0.13.0"
platz-chart-ext = { workspace = true }
regex = "1.10.6"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
titlecase = "3.3.0"
tokio = { version = "1.40.0", features = ["rt-multi-thread", "signal"] }
tracing = "0.1.40"
tracing-subscriber = { workspace = true }
uuid = { version = "1.10.0", features = ["serde", "v4"] }

[dependencies.platz-db]
path = "../db"
