[package]
edition = "2021"
name = "platz-k8s-agent"
version = "0.1.0"

[dependencies]
anyhow = {version = "1.0.75", features = ["backtrace"]}
async-trait = "0.1.73"
aws-arn = "0.3.1"
aws-config = "0.56.1"
aws-sdk-ec2 = "0.30.0"
aws-sdk-eks = "0.30.0"
aws-types = "0.56.1"
base64 = "0.21.2"
chrono = {version = "0.4.26", default-features = false, features = ["std", "serde"]}
clap = {version = "4.4.0", features = ["derive", "env"]}
futures = "0.3.28"
http = "0.2.9"
humantime = "2.1.0"
itertools = "0.11.0"
k8s-openapi = {version = "0.19.0", default-features = false, features = ["v1_21"]}
kube = {version = "0.85.0", default-features = false, features = ["client", "gzip", "ws", "runtime", "rustls-tls"]}
lazy_static = "1.4.0"
log = "0.4.20"
maplit = "1.0.2"
platz-chart-ext = {workspace = true}
serde = {version = "1.0.186", features = ["derive"]}
serde_json = "1.0.105"
serde_yaml = "0.9.25"
tap = "1.0.1"
thiserror = "1.0.47"
tokio = {version = "1.32.0", features = ["full"]}
tokio-stream = "0.1.14"
tokio-util = "0.7.8"
tracing = {version = "0.1.37"}
tracing-subscriber = {workspace=true}
tryhard = "0.5.1"
url = {version = "2.4.0", features = ["serde"]}
uuid = {version = "1.4.1", features = ["serde", "v4"]}

[dependencies.platz-db]
path = "../db"

[dependencies.platz-auth]
path = "../auth"
