[package]
edition = "2021"
name = "platz-k8s-agent"
version = "0.1.0"

[dependencies]
anyhow = {version = "1", features = ["backtrace"]}
async-trait = "0.1.48"
aws-arn = "0.3.1"
aws-config = "0.55.0"
aws-sdk-ec2 = "0.25.0"
aws-sdk-eks = "0.25.0"
aws-types = "0.55.0"
base64 = "0.21.0"
chrono = {version = "0.4", features = ["std", "serde"]}
clap = {version = "4.0.32", features = ["derive", "env"]}
env_logger = "0.10.0"
futures = "0.3.13"
http = "0.2.6"
humantime = '2.1.0'
itertools = "0.10.0"
k8s-openapi = {version = "0.17.0", default-features = false, features = ["v1_21"]}
kube = {version = "0.80.0", default-features = false, features = ["client", "gzip", "ws", "runtime", "rustls-tls"]}
lazy_static = "1"
log = "0.4.14"
maplit = "1"
platz-chart-ext = "0.5.0"
platz-sdk = "0.5.0"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
serde_yaml = "0.9.16"
thiserror = "1.0.30"
tokio = {version = "1", features = ["full"]}
tokio-util = {version = "0.7.1"}
tryhard = "0.5.0"
url = {version = "2.2.2", features = ["serde"]}
uuid = {version = "1", features = ["serde", "v4"]}

[dependencies.platz-db]
path = "../db"

[dependencies.platz-auth]
path = "../auth"
