[package]
edition = "2021"
name = "platz-k8s-agent"
version = "0.1.0"

[dependencies]
anyhow = {version = "1.0.80", features = ["backtrace"]}
aws-arn = "0.3.1"
aws-config = "1.1.6"
aws-sdk-ec2 = "1.20.0"
aws-sdk-eks = "1.15.0"
aws-types = "1.1.6"
base64 = "0.21.7"
chrono = {version = "0.4.34", default-features = false, features = ["std", "serde"]}
clap = {version = "4.5.1", features = ["derive", "env"]}
either = "1.10.0"
futures = "0.3.30"
http = "1.0.0"
humantime = "2.1.0"
itertools = "0.12.1"
k8s-openapi = {version = "0.21.1", features = ["v1_24"]}
kube = {version = "0.88.1", default-features = false, features = [
  "client",
  "config",
  "gzip",
  "ws",
  "runtime",
  "rustls-tls",
]}
lazy_static = "1.4.0"
log = "0.4.20"
maplit = "1.0.2"
platz-chart-ext = {workspace = true}
serde = {version = "1.0.197", features = ["derive"]}
serde_json = "1.0.114"
serde_yaml = "0.9.32"
tap = "1.0.1"
thiserror = "1.0.57"
tokio = {version = "1.36.0", features = ["full"]}
tokio-stream = "0.1.14"
tokio-util = "0.7.10"
tracing = {version = "0.1.40"}
tracing-subscriber = {workspace = true}
tryhard = "0.5.1"
url = {version = "2.5.0", features = ["serde"]}
uuid = {version = "1.7.0", features = ["serde", "v4"]}

[dependencies.platz-db]
path = "../db"

[dependencies.platz-auth]
path = "../auth"
