[package]
edition = "2021"
name = "platz-k8s-agent"
version = "0.1.0"

[dependencies]
anyhow = { version = "1.0.86", features = ["backtrace"] }
aws-arn = "0.3.1"
aws-config = "1.5.4"
aws-sdk-ec2 = "1.60.0"
aws-sdk-eks = "1.40.0"
aws-types = "1.3.3"
base64 = "0.22.1"
chrono = { version = "0.4.38", default-features = false, features = [
  "std",
  "serde",
] }
clap = { version = "4.5.9", features = ["derive", "env"] }
either = "1.13.0"
futures = "0.3.30"
http = "1.1.0"
humantime = "2.1.0"
itertools = "0.13.0"
k8s-openapi = { version = "0.22.0", features = ["v1_24"] }
kube = { version = "0.92.1", default-features = false, features = [
  "client",
  "config",
  "gzip",
  "ws",
  "runtime",
  "rustls-tls",
] }
lazy_static = "1.5.0"
maplit = "1.0.2"
platz-chart-ext = { workspace = true }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
serde_yaml = "0.9.34"
tap = "1.0.1"
thiserror = "1.0.63"
tokio = { version = "1.38.1", features = ["full"] }
tokio-stream = "0.1.15"
tokio-util = "0.7.11"
tracing = { version = "0.1.40" }
tracing-subscriber = { workspace = true }
tryhard = "0.5.1"
url = { version = "2.5.2", features = ["serde"] }
uuid = { version = "1.10.0", features = ["serde", "v4"] }

[dependencies.platz-db]
path = "../db"

[dependencies.platz-auth]
path = "../auth"
