[package]
edition = "2021"
name = "platz-k8s-agent"
version = "0.1.0"

[dependencies]
anyhow = {version = "1.0.71", features = ["backtrace"]}
async-trait = "0.1.71"
aws-arn = "0.3.1"
aws-config = "0.55.3"
aws-sdk-ec2 = "0.28.0"
aws-sdk-eks = "0.28.0"
aws-types = "0.55.3"
base64 = "0.21.2"
chrono = {version = "0.4.26", default-features = false, features = ["std", "serde"]}
clap = {version = "4.3.11", features = ["derive", "env"]}
env_logger = "0.10.0"
futures = "0.3.28"
http = "0.2.9"
humantime = "2.1.0"
itertools = "0.11.0"
k8s-openapi = {version = "0.18.0", default-features = false, features = ["v1_21"]}
kube = {version = "0.83.0", default-features = false, features = ["client", "gzip", "ws", "runtime", "rustls-tls"]}
lazy_static = "1.4.0"
log = "0.4.19"
maplit = "1.0.2"
platz-chart-ext = {workspace = true}
serde = {version = "1.0.171", features = ["derive"]}
serde_json = "1.0.100"
serde_yaml = "0.9.22"
thiserror = "1.0.43"
tokio = {version = "1.29.1", features = ["full"]}
tokio-util = "0.7.8"
tryhard = "0.5.0"
url = {version = "2.4.0", features = ["serde"]}
uuid = {version = "1.4.0", features = ["serde", "v4"]}

[dependencies.platz-db]
path = "../db"

[dependencies.platz-auth]
path = "../auth"
