[package]
edition = "2021"
name = "platz-k8s-agent"
version = "0.1.0"

[dependencies]
anyhow = {version = "1.0.75", features = ["backtrace"]}
async-trait = "0.1.74"
aws-arn = "0.3.1"
aws-config = "1.0.0"
aws-sdk-ec2 = "0.39.1"
aws-sdk-eks = "0.39.0"
aws-types = "1.0.0"
base64 = "0.21.5"
chrono = {version = "0.4.31", default-features = false, features = ["std", "serde"]}
clap = {version = "4.4.8", features = ["derive", "env"]}
either = "1.9.0"
futures = "0.3.29"
http = "1.0.0"
humantime = "2.1.0"
itertools = "0.12.0"
k8s-openapi = {version = "0.20.0", default-features = false, features = ["v1_22"]}
kube = {version = "0.87.1", default-features = false, features = ["client", "gzip", "ws", "runtime", "rustls-tls"]}
lazy_static = "1.4.0"
log = "0.4.20"
maplit = "1.0.2"
platz-chart-ext = {workspace = true}
serde = {version = "1.0.193", features = ["derive"]}
serde_json = "1.0.108"
serde_yaml = "0.9.27"
tap = "1.0.1"
thiserror = "1.0.50"
tokio = {version = "1.34.0", features = ["full"]}
tokio-stream = "0.1.14"
tokio-util = "0.7.10"
tracing = {version = "0.1.40"}
tracing-subscriber = {workspace = true}
tryhard = "0.5.1"
url = {version = "2.4.1", features = ["serde"]}
uuid = {version = "1.6.1", features = ["serde", "v4"]}

[dependencies.platz-db]
path = "../db"

[dependencies.platz-auth]
path = "../auth"
