apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-api
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
      platzService: api
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
        platzService: api
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccount.api.name }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: api
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: '{{ include "chart.backendImage" . }}'
          imagePullPolicy: {{ .Values.images.backend.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          command:
            - /root/platz-api
            - --debug
            - --all-debug
          env:
            - name: DATABASE_URL
              value: '{{ include "chart.databaseUrl" . }}'
            - name: PLATZ_OWN_URL
              value: '{{ include "platz.ownUrl" . }}'
            - name: OIDC_SERVER_URL
              value: '{{ .Values.config.api.auth.oidc_server_url }}'
            - name: OIDC_CLIENT_ID_PARAMETER_NAME
              value: '{{ .Values.config.api.auth.ssm.oidc_client_id }}'
            - name: OIDC_CLIENT_SECRET_PARAMETER_NAME
              value: '{{ .Values.config.api.auth.ssm.oidc_client_secret }}'
            - name: RUST_BACKTRACE
              value: '1'
          livenessProbe:
            httpGet:
              path: /api/v1/status
              port: 3000
          readinessProbe:
            httpGet:
              path: /api/v1/status
              port: 3000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
