apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.taskRunner.name }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.taskRunner.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.serviceAccount.taskRunner.name }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.taskRunner.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
