[package]
edition = "2021"
name = "platz-auth"
version = "0.1.0"

[features]
actix = ["actix-web", "actix-web-httpauth", "futures"]
default = []

[dependencies]
actix-web = {version = "4.8.0", features = ["rustls"], optional = true}
actix-web-httpauth = {version = "0.8.2", optional = true}
base64 = "0.22.1"
chrono = {version = "0.4.38", default-features = false, features = ["std", "serde"]}
clap = "4.5.9"
futures = {version = "0.3.30", optional = true}
jsonwebtoken = "9.3.0"
lazy_static = "1.5.0"
openid = {version = "0.14.0", default-features = false, features = ["rustls"]}
rand = "0.8.5"
serde = {version = "1.0.204", features = ["derive"]}
serde_json = "1.0.120"
sha2 = "0.10.8"
thiserror = "1.0.63"
tokio = "1.38.1"
url = "2.5.2"
utoipa = {version = "4.2.3", features = ["preserve_order"]}
uuid = {version = "1.10.0", features = ["serde", "v4"]}

[dependencies.platz-db]
path = "../db"
