[package]
edition = "2021"
name = "platz-auth"
version = "0.1.0"

[features]
actix = ["actix-web", "actix-web-httpauth", "futures"]
default = []

[dependencies]
actix-web = {version = "4.4.0", features = ["rustls"], optional = true}
actix-web-httpauth = {version = "0.8.1", optional = true}
base64 = "0.21.5"
chrono = {version = "0.4.31", default-features = false, features = ["std", "serde"]}
clap = "4.4.8"
futures = {version = "0.3.29", optional = true}
jsonwebtoken = "9.1.0"
lazy_static = "1.4.0"
openid = {version = "0.12.1", default-features = false, features = ["rustls"]}
rand = "0.8.5"
serde = {version = "1.0.193", features = ["derive"]}
serde_json = "1.0.108"
sha2 = "0.10.8"
thiserror = "1.0.50"
tokio = "1.34.0"
url = "2.4.1"
utoipa = {version = "4.1.0", features = ["preserve_order"]}
uuid = {version = "1.6.1", features = ["serde", "v4"]}

[dependencies.platz-db]
path = "../db"
