[package]
edition = "2021"
name = "platz-resource-sync"
version = "0.1.0"

[dependencies]
anyhow = "1.0.43"
env_logger = "0.9.0"
itertools = "0.10.1"
log = "0.4.14"
reqwest = {version = "0.11.4", features = ["rustls-tls", "json"]}
serde = {version = "1.0.130", features = ["derive"]}
serde_json = "1"
structopt = "0.3.22"
tokio = {version = "1", features = ["full"]}

[dependencies.platz-chart-ext]
path = "../chart-ext"

[dependencies.platz-db]
path = "../db"
