[package]
edition = "2021"
name = "platz-resource-sync"
version = "0.1.0"

[dependencies]
anyhow = "1.0.43"
clap = {version = "3.1.6", features = ["derive"]}
env_logger = "0.9.0"
itertools = "0.10.1"
log = "0.4.14"
platz-chart-ext = {version = "0.4.0", default-features = false, features = ["uuid08"]}
reqwest = {version = "0.11.4", features = ["rustls-tls", "json"]}
serde = {version = "1.0.130", features = ["derive"]}
serde_json = "1"
tokio = {version = "1", features = ["full"]}

[dependencies.platz-db]
path = "../db"
