[package]
edition = "2021"
name = "platz-resource-sync"
version = "0.1.0"

[dependencies]
anyhow = "1.0.71"
clap = {version = "4.3.11", features = ["derive"]}
env_logger = "0.10.0"
itertools = "0.11.0"
log = "0.4.19"
platz-chart-ext = {workspace = true}
reqwest = {version = "0.11.18", default-features = false, features = ["rustls-tls", "json"]}
serde = {version = "1.0.171", features = ["derive"]}
serde_json = "1.0.100"
tokio = {version = "1.29.1", features = ["full"]}

[dependencies.platz-db]
path = "../db"
