[package]
edition = "2021"
name = "platz-resource-sync"
version = "0.1.0"

[dependencies]
anyhow = "1.0.86"
clap = {version = "4.5.9", features = ["derive"]}
itertools = "0.13.0"
platz-chart-ext = {workspace = true}
reqwest = {version = "0.12.5", default-features = false, features = ["rustls-tls", "json"]}
serde = {version = "1.0.204", features = ["derive"]}
serde_json = "1.0.120"
tokio = {version = "1.38.1", features = ["full"]}
tracing = "0.1.40"
tracing-subscriber = {workspace = true}

[dependencies.platz-db]
path = "../db"
