[package]
edition = "2021"
name = "platz-resource-sync"
version = "0.1.0"

[dependencies]
anyhow = "1.0.79"
clap = {version = "4.4.18", features = ["derive"]}
itertools = "0.12.1"
log = "0.4.20"
platz-chart-ext = {workspace = true}
reqwest = {version = "0.11.24", default-features = false, features = ["rustls-tls", "json"]}
serde = {version = "1.0.196", features = ["derive"]}
serde_json = "1.0.113"
tokio = {version = "1.35.1", features = ["full"]}
tracing-subscriber = {workspace=true}

[dependencies.platz-db]
path = "../db"
