[package]
edition = "2021"
name = "platz-db"
version = "0.1.0"

[dependencies]
anyhow = "1.0.75"
async-diesel = {git = "https://github.com/vmalloc/async-diesel2.git", branch = "diesel-2.0"}
async-trait = "0.1.73"
chrono = {version = "0.4.26", default-features = false, features = ["std", "serde"]}
diesel_enum_derive = {git = "https://github.com/popen2/diesel-enum-derive", default-features = false, features = ["plain"]}
diesel_json = "0.2.1"
diesel_migrations = "2.1.0"
itertools = "0.11.0"
lazy_static = "1.4.0"
log = "0.4.20"
maplit = "1.0.2"
platz-chart-ext = {workspace = true}
postgres = "0.19.6"
r2d2 = "0.8.10"
rust_decimal = {version = "1.32.0", default-features = false, features = ["db-diesel-postgres"]}
serde = {version = "1.0.186", features = ["derive"]}
serde_json = "1.0.105"
serde_with = "3.3.0"
strum = {version = "0.25.0", features = ["derive"]}
thiserror = "1.0.47"
tokio = {version = "1.32.0", features = ["full"]}
url = "2.4.0"
utoipa = {version = "3.5.0", features = ["chrono", "decimal", "preserve_order", "uuid"]}
uuid = {version = "1.4.1", features = ["serde", "v4"]}

[dependencies.diesel]
features = [
  "chrono",
  "numeric",
  "postgres",
  "r2d2",
  "serde_json",
  "uuid",
]
version = "2.1.1"

[dependencies.diesel_filter]
features = [
  "actix",
  "diesel",
  "serde",
  "serialize",
  "pagination",
  "utoipa",
]
git = "https://github.com/popen2/diesel_filter"
