[package]
edition = "2021"
name = "platz-db"
version = "0.1.0"

[dependencies]
anyhow = "1"
async-diesel = {git = "https://github.com/vmalloc/async-diesel2.git", branch = "diesel-2.0"}
async-trait = "0.1.52"
chrono = {version = "0.4", default-features = false, features = ["std", "serde"]}
diesel_enum_derive = {git = "https://github.com/popen2/diesel-enum-derive", default-features = false, features = ["plain"]}
diesel_json = "0.2.0"
diesel_migrations = "2.0.0"
itertools = "0.10.1"
lazy_static = "1"
log = "0.4.14"
maplit = "1"
platz-chart-ext = {version = "0.5.5", features = ["utoipa"]}
postgres = "0.19.0"
r2d2 = "0.8.9"
rust_decimal = {version = "1.14.0", default-features = false, features = ["db-diesel-postgres"]}
serde = {version = "1", features = ["derive"]}
serde_json = "1"
serde_with = "3.0.0"
strum = {version = "0.24.0", features = ["derive"]}
thiserror = "1.0.29"
tokio = {version = "1", features = ["full"]}
url = "2.2.2"
utoipa = {version = "3.3.0", features = ["chrono", "decimal", "preserve_order", "uuid"]}
uuid = {version = "1", features = ["serde", "v4"]}

[dependencies.diesel]
features = [
  "chrono",
  "numeric",
  "postgres",
  "r2d2",
  "serde_json",
  "uuid",
]
version = "2.0.3"

[dependencies.diesel_filter]
features = [
  "actix",
  "diesel",
  "serde",
  "serialize",
  "pagination",
  "utoipa",
]
git = "https://github.com/popen2/diesel_filter"
