[package]
edition = "2021"
name = "platz-db"
version = "0.1.0"

[dependencies]
anyhow = "1"
async-diesel = {git = "https://github.com/mehcode/async-diesel.git"}
async-trait = "0.1.52"
chrono = {version = "0.4", features = ["std", "serde"]}
diesel-derive-more = "1.1.3"
diesel_json = "0.1.1"
diesel_migrations = "1.4.0"
itertools = "0.10.1"
lazy_static = "1"
log = "0.4.14"
maplit = "1"
postgres = "0.19.0"
rust_decimal = {version = "1.14.0", features = ["db-diesel-postgres"]}
serde = {version = "1", features = ["derive"]}
serde_json = "1"
serde_with = "1.10.0"
strum = {version = "0.24.0", features = ["derive"]}
thiserror = "1.0.29"
tokio = {version = "1", features = ["full"]}
uuid = {version = "0.8", features = ["serde", "v4"]}

[dependencies.diesel]
features = [
  "chrono",
  "numeric",
  "postgres",
  "r2d2",
  "serde_json",
  "uuidv07",
]
version = "1.4"

[dependencies.platz-ui-schema]
path = "../ui-schema"
