[package]
edition = "2021"
name = "platz-db"
version = "0.1.0"

[dependencies]
anyhow = "1.0.95"
chrono = { version = "0.4.39", default-features = false, features = [
  "std",
  "serde",
] }
diesel = { version = "2.2.6", features = [
  "chrono",
  "numeric",
  "serde_json",
  "uuid",
] }
diesel-async = { version = "0.5.2", features = [
  "async-connection-wrapper",
  "bb8",
  "postgres",
] }
diesel_enum_derive = { git = "https://github.com/popen2/diesel-enum-derive", default-features = false, features = [
  "plain",
] }
diesel_json = "0.2.1"
diesel_migrations = "2.2.0"
itertools = "0.14.0"
lazy_static = "1.5.0"
maplit = "1.0.2"
platz-chart-ext = { workspace = true }
prometheus = { workspace = true }
rust_decimal = { version = "1.36.0", default-features = false, features = [
  "db-diesel-postgres",
] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
serde_with = "3.12.0"
strum = { version = "0.26.3", features = ["derive"] }
thiserror = "2.0.11"
tokio = "1.43.0"
tokio-postgres = "0.7.12"
tracing = "0.1.41"
url = "2.5.4"
utoipa = { version = "5.3.1", features = [
  "chrono",
  "decimal",
  "preserve_order",
  "uuid",
] }
uuid = { version = "1.12.1", features = ["serde", "v4"] }

[dependencies.diesel_filter]
features = [
  "actix",
  "diesel_async",
  "serde",
  "serialize",
  "pagination",
  "utoipa",
]
git = "https://github.com/popen2/diesel_filter"
tag = "v1.0.4"
