issuer: http://127.0.0.1:5556

storage:
  type: sqlite3
  config:
    file: /tmp/dex.db

web:
  http: 0.0.0.0:5556

telemetry:
  http: 0.0.0.0:5558

grpc:
  addr: 0.0.0.0:5557

staticClients:
  - id: platz
    redirectURIs:
      - "http://127.0.0.1:5173/auth/google/callback"
      - "https://127.0.0.1:5173/auth/google/callback"
    name: "Platz"
    secret: platz

connectors:
  - type: mockCallback
    id: mock
    name: Example

enablePasswordDB: true

staticPasswords:
  - email: "admin@example.com"
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
    username: "admin"
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
