[package]
edition = "2021"
name = "platz-api"
version = "0.1.0"

[dependencies]
actix = "0.12.0"
actix-web = {version = "4.0.0-beta.4", features = ["rustls"]}
actix-web-actors = "4.0.0-beta.3"
actix-web-httpauth = "0.6.0-beta.2"
anyhow = {version = "1", features = ["backtrace"]}
base64 = "0.13.0"
chrono = {version = "0.4", features = ["std", "serde"]}
env_logger = "0.9.0"
futures = "0.3.21"
itertools = "0.10.0"
jsonwebtoken = "7.2.0"
log = "0.4.14"
openid = {version = "0.9", default-features = false, features = ["rustls"]}
rand = "0.8.4"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
structopt = "0.3.21"
thiserror = "1"
tokio = {version = "1", features = ["full"]}
tokio-stream = {version = "0.1.5", features = ["sync"]}
url = "2"
uuid = {version = "0.8", features = ["serde", "v4"]}

[dependencies.platz-chart-ext]
path = "../chart-ext"

[dependencies.platz-db]
path = "../db"
