[package]
edition = "2021"
name = "platz-api"
version = "0.1.0"

[dependencies]
actix = "0.13.1"
actix-web = {version = "4.4.0", features = ["rustls"]}
actix-web-actors = "4.2.0"
anyhow = {version = "1.0.75", features = ["backtrace"]}
chrono = {version = "0.4.31", default-features = false, features = ["std", "serde"]}
clap = {version = "4.4.8", features = ["derive", "env"]}
dotenvy = "0.15.7"
futures = "0.3.29"
humantime = "2.1.0"
itertools = "0.12.0"
lazy_static = "1.4.0"
log = "0.4.20"
platz-chart-ext = {workspace = true}
prometheus = {workspace = true}
regex = "1.10.2"
serde = {version = "1.0.193", features = ["derive"]}
serde_json = "1.0.108"
strum = "0.25.0"
thiserror = "1.0.50"
tokio = {version = "1.34.0", features = ["full"]}
tokio-stream = {version = "0.1.14", features = ["sync"]}
tracing-subscriber = {workspace = true}
url = "2.4.1"
utoipa = {version = "4.1.0", features = [
  "actix_extras",
  "chrono",
  "decimal",
  "preserve_order",
  "uuid",
  "yaml",
]}
uuid = {version = "1.6.1", features = ["serde", "v4"]}

[dependencies.platz-db]
path = "../db"

[dependencies.platz-auth]
features = ["actix"]
path = "../auth"
