[package]
edition = "2021"
name = "platz-api"
version = "0.1.0"

[dependencies]
actix = "0.13.0"
actix-web = { version = "4.0.0", features = ["rustls"] }
actix-web-actors = "4.0.0"
anyhow = { version = "1", features = ["backtrace"] }
clap = { version = "4.0.32", features = ["derive", "env"] }
env_logger = "0.10.0"
futures = "0.3.21"
itertools = "0.10.0"
lazy_static = "1.4.0"
log = "0.4.14"
platz-chart-ext = { version = "0.4.0", default-features = false, features = [
    "uuid08",
] }
regex = "1.5.6"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1.5", features = ["sync"] }
url = "2"
uuid = { version = "0.8", features = ["serde", "v4"] }
dotenvy = "0.15.6"

[dependencies.platz-db]
path = "../db"

[dependencies.platz-auth]
features = ["actix"]
path = "../auth"
