[package]
edition = "2021"
name = "platz-api"
version = "0.1.0"

[dependencies]
actix = "0.13.3"
actix-web = {version = "4.5.1", features = ["rustls"]}
actix-web-actors = "4.3.0"
anyhow = {version = "1.0.80", features = ["backtrace"]}
chrono = {version = "0.4.34", default-features = false, features = ["std", "serde"]}
clap = {version = "4.5.1", features = ["derive", "env"]}
dotenvy = "0.15.7"
futures = "0.3.30"
humantime = "2.1.0"
itertools = "0.12.1"
lazy_static = "1.4.0"
log = "0.4.20"
platz-chart-ext = {workspace = true}
prometheus = {workspace = true}
regex = "1.10.3"
serde = {version = "1.0.197", features = ["derive"]}
serde_json = "1.0.114"
strum = "0.26.1"
thiserror = "1.0.57"
tokio = {version = "1.36.0", features = ["full"]}
tokio-stream = {version = "0.1.14", features = ["sync"]}
tracing-subscriber = {workspace = true}
url = "2.5.0"
utoipa = {version = "4.2.0", features = [
  "actix_extras",
  "chrono",
  "decimal",
  "preserve_order",
  "uuid",
  "yaml",
]}
uuid = {version = "1.7.0", features = ["serde", "v4"]}

[dependencies.platz-db]
path = "../db"

[dependencies.platz-auth]
features = ["actix"]
path = "../auth"
